// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Property struct {
	ID      int64       `json:"id"`
	UserID  int64       `json:"user_id"`
	Name    string      `json:"name"`
	PhotoID pgtype.Int8 `json:"photo_id"`
}

type User struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	RefreshToken pgtype.Text `json:"refresh_token"`
}
