// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: property.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (user_id, name, photo_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, photo_id
`

type CreatePropertyParams struct {
	UserID  int64       `json:"user_id"`
	Name    string      `json:"name"`
	PhotoID pgtype.Int8 `json:"photo_id"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty, arg.UserID, arg.Name, arg.PhotoID)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PhotoID,
	)
	return i, err
}
