// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRefreshToken = `-- name: AddRefreshToken :execrows
UPDATE "user"
SET refresh_token = $1
WHERE email = $2
`

type AddRefreshTokenParams struct {
	RefreshToken pgtype.Text `json:"refresh_token"`
	Email        string      `json:"email"`
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, addRefreshToken, arg.RefreshToken, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, password)
VALUES ($1, $2, $3)
RETURNING id, name, email
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const fetchUserByID = `-- name: FetchUserByID :one
SELECT id, name, email
FROM public."user"
WHERE id = $1
`

type FetchUserByIDRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) FetchUserByID(ctx context.Context, id int64) (FetchUserByIDRow, error) {
	row := q.db.QueryRow(ctx, fetchUserByID, id)
	var i FetchUserByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id FROM public."user" WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email FROM public."user"
`

type ListUsersRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRefreshToken = `-- name: RemoveRefreshToken :execrows
UPDATE "user" SET refresh_token = NULL WHERE refresh_token = $1
`

func (q *Queries) RemoveRefreshToken(ctx context.Context, refreshToken pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, removeRefreshToken, refreshToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const verifyPassword = `-- name: VerifyPassword :one
SELECT id, password FROM public."user" WHERE email = $1
`

type VerifyPasswordRow struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) VerifyPassword(ctx context.Context, email string) (VerifyPasswordRow, error) {
	row := q.db.QueryRow(ctx, verifyPassword, email)
	var i VerifyPasswordRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const verifyRefreshToken = `-- name: VerifyRefreshToken :one
SELECT id, name, email FROM public."user" WHERE refresh_token = $1
`

type VerifyRefreshTokenRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) VerifyRefreshToken(ctx context.Context, refreshToken pgtype.Text) (VerifyRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, verifyRefreshToken, refreshToken)
	var i VerifyRefreshTokenRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
